import type { Id, ProcessModel, ViewDef } from "./model.js";

export type SampleProcess = Readonly<{
  id: string;
  title: string;
  rootActivityId: Id;
  model: ProcessModel;
}>;

const HIERARCHICAL_VIEWS: readonly ViewDef[] = [
  { id: "person_view", layout: "lane", boundary: "person", normalForm: "responsibilityBoundary" },
  { id: "team_view", layout: "lane", boundary: "team", normalForm: "responsibilityBoundary" },
  { id: "section_view", layout: "lane", boundary: "section", normalForm: "responsibilityBoundary" },
  {
    id: "department_view",
    layout: "lane",
    boundary: "department",
    normalForm: "responsibilityBoundary",
  },
  { id: "company_view", layout: "lane", boundary: "company", normalForm: "responsibilityBoundary" },
];

// ソフトウェア開発: 実装とレビューが同一チーム内で連続し、開発⇄QA の差し戻しが
// 部門境界をまたいで往復する。ズームを上げると開発部の連続ステップが大きく合成され、
// 一方で差し戻しの往復は境界越えとして残る。
const softwareDevelopment: ProcessModel = {
  schemaVersion: "responsible.v0",
  activities: {
    software_development: {
      id: "software_development",
      name: "ソフトウェア開発",
      input: "未整理Issue",
      output: "リリース",
      status: "defined",
      children: [
        "issue_triage",
        "requirements",
        "design",
        "design_review",
        "implementation_loop",
        "test",
        "bug_report",
        "bug_fix",
        "retest",
        "release",
      ],
      responsibility: { company: "あかつきソフトウェア" },
    },
    issue_triage: {
      id: "issue_triage",
      name: "Issueを分類する",
      input: "未整理Issue",
      output: "分類済みIssue",
      status: "defined",
      responsibility: {
        company: "あかつきソフトウェア",
        department: "プロダクト部",
        section: "プロダクト管理課",
        team: "トリアージチーム",
        person: "佐藤",
      },
    },
    requirements: {
      id: "requirements",
      name: "要件を整理する",
      input: "分類済みIssue",
      output: "要件定義",
      status: "defined",
      responsibility: {
        company: "あかつきソフトウェア",
        department: "プロダクト部",
        section: "プロダクト管理課",
        team: "トリアージチーム",
        person: "佐藤",
      },
    },
    design: {
      id: "design",
      name: "設計する",
      input: "要件定義",
      output: "設計書",
      status: "defined",
      responsibility: {
        company: "あかつきソフトウェア",
        department: "開発部",
        section: "アーキテクチャ課",
        team: "設計チーム",
        person: "鈴木",
      },
    },
    design_review: {
      id: "design_review",
      name: "設計をレビューする",
      input: "設計書",
      output: "承認済み設計",
      status: "validated",
      responsibility: {
        company: "あかつきソフトウェア",
        department: "開発部",
        section: "アーキテクチャ課",
        team: "設計チーム",
        person: "渡辺",
      },
    },
    implementation_loop: {
      id: "implementation_loop",
      name: "実装とレビュー",
      input: "承認済み設計",
      output: "レビュー済みPR",
      status: "defined",
      children: ["implementation", "self_review", "code_review", "fix"],
      responsibility: {
        company: "あかつきソフトウェア",
        department: "開発部",
        section: "アプリケーション課",
        team: "機能開発チーム",
      },
    },
    implementation: {
      id: "implementation",
      name: "実装する",
      input: "承認済み設計",
      output: "差分",
      status: "defined",
      responsibility: {
        company: "あかつきソフトウェア",
        department: "開発部",
        section: "アプリケーション課",
        team: "機能開発チーム",
        person: "高橋",
      },
    },
    self_review: {
      id: "self_review",
      name: "セルフレビューする",
      input: "差分",
      output: "プルリクエスト",
      status: "defined",
      responsibility: {
        company: "あかつきソフトウェア",
        department: "開発部",
        section: "アプリケーション課",
        team: "機能開発チーム",
        person: "高橋",
      },
    },
    code_review: {
      id: "code_review",
      name: "コードレビューする",
      input: "プルリクエスト",
      output: "指摘事項",
      status: "validated",
      responsibility: {
        company: "あかつきソフトウェア",
        department: "開発部",
        section: "アプリケーション課",
        team: "機能開発チーム",
        person: "田中",
      },
    },
    fix: {
      id: "fix",
      name: "指摘を修正する",
      input: "指摘事項",
      output: "レビュー済みPR",
      status: "defined",
      responsibility: {
        company: "あかつきソフトウェア",
        department: "開発部",
        section: "アプリケーション課",
        team: "機能開発チーム",
        person: "高橋",
      },
    },
    test: {
      id: "test",
      name: "テストする",
      input: "レビュー済みPR",
      output: "テスト結果",
      status: "validated",
      responsibility: {
        company: "あかつきソフトウェア",
        department: "品質保証部",
        section: "QA課",
        team: "テストチーム",
        person: "伊藤",
      },
    },
    bug_report: {
      id: "bug_report",
      name: "不具合を報告する",
      input: "テスト結果",
      output: "不具合チケット",
      status: "validated",
      responsibility: {
        company: "あかつきソフトウェア",
        department: "品質保証部",
        section: "QA課",
        team: "テストチーム",
        person: "伊藤",
      },
    },
    bug_fix: {
      id: "bug_fix",
      name: "不具合を修正する",
      input: "不具合チケット",
      output: "修正ビルド",
      status: "defined",
      responsibility: {
        company: "あかつきソフトウェア",
        department: "開発部",
        section: "アプリケーション課",
        team: "機能開発チーム",
        person: "高橋",
      },
    },
    retest: {
      id: "retest",
      name: "再テストする",
      input: "修正ビルド",
      output: "テスト済みビルド",
      status: "validated",
      responsibility: {
        company: "あかつきソフトウェア",
        department: "品質保証部",
        section: "QA課",
        team: "テストチーム",
        person: "伊藤",
      },
    },
    release: {
      id: "release",
      name: "リリースする",
      input: "テスト済みビルド",
      output: "リリース",
      status: "automatable",
      responsibility: {
        company: "あかつきソフトウェア",
        department: "基盤部",
        section: "リリース管理課",
        team: "運用チーム",
        person: "小林",
      },
    },
  },
  flows: [
    { from: "issue_triage", to: "requirements", contract: "分類済みIssueが要件整理に渡せる" },
    { from: "requirements", to: "design", contract: "要件定義が設計に渡せる" },
    { from: "design", to: "design_review", contract: "設計書がレビュー可能" },
    { from: "design_review", to: "implementation", contract: "承認済み設計が実装に渡せる" },
    { from: "implementation", to: "self_review", contract: "差分がセルフレビュー可能" },
    { from: "self_review", to: "code_review", contract: "プルリクエストがレビュー可能" },
    { from: "code_review", to: "fix", contract: "指摘事項が修正に渡せる" },
    { from: "fix", to: "test", contract: "レビュー済みPRがテスト可能" },
    { from: "test", to: "bug_report", contract: "テスト結果が報告にまとめられる" },
    { from: "bug_report", to: "bug_fix", contract: "不具合チケットが修正に渡せる" },
    { from: "bug_fix", to: "retest", contract: "修正ビルドが再テスト可能" },
    { from: "retest", to: "release", contract: "テスト済みビルドがリリース可能" },
  ],
  views: HIERARCHICAL_VIEWS,
};

// 文書公開: 制作部内でライターと編集が往復し、統制部での審査を経て公開へ進む。
// 編集の差し戻しが制作部内で起こり、法務・承認は統制部に合成される。
const documentPublishing: ProcessModel = {
  schemaVersion: "responsible.v0",
  activities: {
    document_publishing: {
      id: "document_publishing",
      name: "文書公開",
      input: "企画案",
      output: "保管記録",
      status: "defined",
      children: [
        "planning",
        "draft",
        "polish",
        "edit_review",
        "revise",
        "proofread",
        "legal_check",
        "approve",
        "publish",
        "measure",
        "archive",
      ],
      responsibility: { company: "ビーコンメディア" },
    },
    planning: {
      id: "planning",
      name: "構成を企画する",
      input: "企画案",
      output: "構成案",
      status: "defined",
      responsibility: {
        company: "ビーコンメディア",
        department: "制作部",
        section: "編集課",
        team: "編集チーム",
        person: "三浦",
      },
    },
    draft: {
      id: "draft",
      name: "下書きを作成する",
      input: "構成案",
      output: "下書き",
      status: "defined",
      responsibility: {
        company: "ビーコンメディア",
        department: "制作部",
        section: "ライター課",
        team: "文書チーム",
        person: "中村",
      },
    },
    polish: {
      id: "polish",
      name: "推敲する",
      input: "下書き",
      output: "推敲済み下書き",
      status: "defined",
      responsibility: {
        company: "ビーコンメディア",
        department: "制作部",
        section: "ライター課",
        team: "文書チーム",
        person: "中村",
      },
    },
    edit_review: {
      id: "edit_review",
      name: "編集レビューする",
      input: "推敲済み下書き",
      output: "編集指摘",
      status: "validated",
      responsibility: {
        company: "ビーコンメディア",
        department: "制作部",
        section: "編集課",
        team: "編集チーム",
        person: "大野",
      },
    },
    revise: {
      id: "revise",
      name: "修正する",
      input: "編集指摘",
      output: "修正版",
      status: "defined",
      responsibility: {
        company: "ビーコンメディア",
        department: "制作部",
        section: "ライター課",
        team: "文書チーム",
        person: "中村",
      },
    },
    proofread: {
      id: "proofread",
      name: "校正する",
      input: "修正版",
      output: "校正済み原稿",
      status: "validated",
      responsibility: {
        company: "ビーコンメディア",
        department: "制作部",
        section: "校正課",
        team: "校正チーム",
        person: "林",
      },
    },
    legal_check: {
      id: "legal_check",
      name: "法務確認する",
      input: "校正済み原稿",
      output: "法務確認済み原稿",
      status: "validated",
      responsibility: {
        company: "ビーコンメディア",
        department: "統制部",
        section: "審査課",
        team: "法務チーム",
        person: "森",
      },
    },
    approve: {
      id: "approve",
      name: "公開を承認する",
      input: "法務確認済み原稿",
      output: "承認済み文書",
      status: "validated",
      responsibility: {
        company: "ビーコンメディア",
        department: "統制部",
        section: "審査課",
        team: "承認チーム",
        person: "岡",
      },
    },
    publish: {
      id: "publish",
      name: "公開する",
      input: "承認済み文書",
      output: "公開済み文書",
      status: "automatable",
      responsibility: {
        company: "ビーコンメディア",
        department: "基盤部",
        section: "Web課",
        team: "公開チーム",
        person: "山本",
      },
    },
    measure: {
      id: "measure",
      name: "効果を測定する",
      input: "公開済み文書",
      output: "効果レポート",
      status: "automatable",
      responsibility: {
        company: "ビーコンメディア",
        department: "基盤部",
        section: "Web課",
        team: "公開チーム",
        person: "山本",
      },
    },
    archive: {
      id: "archive",
      name: "記録を保管する",
      input: "効果レポート",
      output: "保管記録",
      status: "automatable",
      responsibility: {
        company: "ビーコンメディア",
        department: "基盤部",
        section: "記録管理課",
        team: "保管チーム",
        person: "吉田",
      },
    },
  },
  flows: [
    { from: "planning", to: "draft", contract: "構成案が下書きに渡せる" },
    { from: "draft", to: "polish", contract: "下書きが推敲可能" },
    { from: "polish", to: "edit_review", contract: "推敲済み下書きがレビュー可能" },
    { from: "edit_review", to: "revise", contract: "編集指摘が修正に渡せる" },
    { from: "revise", to: "proofread", contract: "修正版が校正可能" },
    { from: "proofread", to: "legal_check", contract: "校正済み原稿が法務確認に渡せる" },
    { from: "legal_check", to: "approve", contract: "法務確認済み原稿が承認可能" },
    { from: "approve", to: "publish", contract: "承認済み文書が公開可能" },
    { from: "publish", to: "measure", contract: "公開済み文書の効果を測定できる" },
    { from: "measure", to: "archive", contract: "効果レポートを保管できる" },
  ],
  views: HIERARCHICAL_VIEWS,
};

// AIエージェント実行: 1トレースを展開した実行系列。計画→ツール実行→検証のループが
// 推論課・実行課を往復する。担当者レベルでは細かく分かれるが、部門レベルでは
// 実行基盤部が中間の全ステップを1つに飲み込み、インターフェース部が前後に残る。
const aiAgentExecution: ProcessModel = {
  schemaVersion: "responsible.v0",
  activities: {
    ai_agent_execution: {
      id: "ai_agent_execution",
      name: "AIエージェント実行",
      input: "ユーザー発話",
      output: "アシスタント応答",
      status: "defined",
      children: [
        "intake",
        "validate_input",
        "fetch_context",
        "search_docs",
        "make_plan",
        "select_tool",
        "run_tool",
        "observe_result",
        "verify_result",
        "revise_plan",
        "rerun_tool",
        "finalize",
        "compose_reply",
        "respond",
      ],
      responsibility: { company: "エージェント基盤" },
    },
    intake: {
      id: "intake",
      name: "依頼を受け付ける",
      input: "ユーザー発話",
      output: "受理済み依頼",
      status: "defined",
      responsibility: {
        company: "エージェント基盤",
        department: "インターフェース部",
        section: "窓口課",
        team: "対話チーム",
        person: "ゲートウェイ",
      },
    },
    validate_input: {
      id: "validate_input",
      name: "入力を検証する",
      input: "受理済み依頼",
      output: "解釈済み依頼",
      status: "defined",
      responsibility: {
        company: "エージェント基盤",
        department: "インターフェース部",
        section: "窓口課",
        team: "対話チーム",
        person: "ゲートウェイ",
      },
    },
    fetch_context: {
      id: "fetch_context",
      name: "文脈を取得する",
      input: "解釈済み依頼",
      output: "会話文脈",
      status: "defined",
      responsibility: {
        company: "エージェント基盤",
        department: "実行基盤部",
        section: "検索課",
        team: "文脈チーム",
        person: "リトリーバー",
      },
    },
    search_docs: {
      id: "search_docs",
      name: "関連文書を検索する",
      input: "会話文脈",
      output: "根拠文書",
      status: "defined",
      responsibility: {
        company: "エージェント基盤",
        department: "実行基盤部",
        section: "検索課",
        team: "文脈チーム",
        person: "サーチャー",
      },
    },
    make_plan: {
      id: "make_plan",
      name: "計画を立てる",
      input: "根拠文書",
      output: "実行計画",
      status: "defined",
      responsibility: {
        company: "エージェント基盤",
        department: "実行基盤部",
        section: "推論課",
        team: "計画チーム",
        person: "プランナー",
      },
    },
    select_tool: {
      id: "select_tool",
      name: "ツールを選ぶ",
      input: "実行計画",
      output: "ツール呼び出し",
      status: "defined",
      responsibility: {
        company: "エージェント基盤",
        department: "実行基盤部",
        section: "推論課",
        team: "計画チーム",
        person: "プランナー",
      },
    },
    run_tool: {
      id: "run_tool",
      name: "ツールを実行する",
      input: "ツール呼び出し",
      output: "ツール出力",
      status: "validated",
      responsibility: {
        company: "エージェント基盤",
        department: "実行基盤部",
        section: "実行課",
        team: "ツールチーム",
        person: "エグゼキューター",
      },
    },
    observe_result: {
      id: "observe_result",
      name: "結果を観測する",
      input: "ツール出力",
      output: "観測結果",
      status: "validated",
      responsibility: {
        company: "エージェント基盤",
        department: "実行基盤部",
        section: "実行課",
        team: "ツールチーム",
        person: "エグゼキューター",
      },
    },
    verify_result: {
      id: "verify_result",
      name: "結果を検証する",
      input: "観測結果",
      output: "検証判定",
      status: "validated",
      responsibility: {
        company: "エージェント基盤",
        department: "実行基盤部",
        section: "推論課",
        team: "検証チーム",
        person: "ベリファイア",
      },
    },
    revise_plan: {
      id: "revise_plan",
      name: "計画を見直す",
      input: "検証判定",
      output: "修正計画",
      status: "defined",
      responsibility: {
        company: "エージェント基盤",
        department: "実行基盤部",
        section: "推論課",
        team: "計画チーム",
        person: "プランナー",
      },
    },
    rerun_tool: {
      id: "rerun_tool",
      name: "ツールを再実行する",
      input: "修正計画",
      output: "再実行結果",
      status: "validated",
      responsibility: {
        company: "エージェント基盤",
        department: "実行基盤部",
        section: "実行課",
        team: "ツールチーム",
        person: "エグゼキューター",
      },
    },
    finalize: {
      id: "finalize",
      name: "最終結果をまとめる",
      input: "再実行結果",
      output: "確定結果",
      status: "validated",
      responsibility: {
        company: "エージェント基盤",
        department: "実行基盤部",
        section: "推論課",
        team: "検証チーム",
        person: "ベリファイア",
      },
    },
    compose_reply: {
      id: "compose_reply",
      name: "応答を生成する",
      input: "確定結果",
      output: "応答草案",
      status: "automatable",
      responsibility: {
        company: "エージェント基盤",
        department: "インターフェース部",
        section: "窓口課",
        team: "対話チーム",
        person: "ゲートウェイ",
      },
    },
    respond: {
      id: "respond",
      name: "応答を返す",
      input: "応答草案",
      output: "アシスタント応答",
      status: "automatable",
      responsibility: {
        company: "エージェント基盤",
        department: "インターフェース部",
        section: "窓口課",
        team: "対話チーム",
        person: "ゲートウェイ",
      },
    },
  },
  flows: [
    { from: "intake", to: "validate_input", contract: "受理済み依頼が検証可能" },
    { from: "validate_input", to: "fetch_context", contract: "解釈済み依頼で文脈取得できる" },
    { from: "fetch_context", to: "search_docs", contract: "会話文脈で文書検索できる" },
    { from: "search_docs", to: "make_plan", contract: "根拠文書で計画を立てられる" },
    { from: "make_plan", to: "select_tool", contract: "実行計画からツールを選べる" },
    { from: "select_tool", to: "run_tool", contract: "ツール呼び出しが実行可能" },
    { from: "run_tool", to: "observe_result", contract: "ツール出力を観測できる" },
    { from: "observe_result", to: "verify_result", contract: "観測結果を検証できる" },
    { from: "verify_result", to: "revise_plan", contract: "検証判定で計画を見直せる" },
    { from: "revise_plan", to: "rerun_tool", contract: "修正計画でツールを再実行できる" },
    { from: "rerun_tool", to: "finalize", contract: "再実行結果をまとめられる" },
    { from: "finalize", to: "compose_reply", contract: "確定結果から応答を生成できる" },
    { from: "compose_reply", to: "respond", contract: "応答草案を返せる" },
  ],
  views: HIERARCHICAL_VIEWS,
};

export const sampleProcesses: readonly SampleProcess[] = [
  {
    id: "software_development",
    title: "ソフトウェア開発",
    rootActivityId: "software_development",
    model: softwareDevelopment,
  },
  {
    id: "document_publishing",
    title: "文書公開",
    rootActivityId: "document_publishing",
    model: documentPublishing,
  },
  {
    id: "ai_agent_execution",
    title: "AIエージェント実行",
    rootActivityId: "ai_agent_execution",
    model: aiAgentExecution,
  },
];

export const rootActivityId: Id = sampleProcesses[0]!.rootActivityId;
export const sampleModel: ProcessModel = sampleProcesses[0]!.model;
