import type { ProcessModel } from "./model.js";

export const rootActivityId = "receive_contract_process";

export const sampleModel: ProcessModel = {
  schemaVersion: "responsible.v0",
  activities: {
    receive_contract_process: {
      id: "receive_contract_process",
      name: "契約から請求まで",
      input: "CustomerInquiry",
      output: "Invoice",
      status: "defined",
      children: ["receive_order", "execute_project", "bill_customer"],
      responsibility: {
        company: "Example Construction",
        function: "project_delivery",
        project: "Project A",
      },
    },
    receive_order: {
      id: "receive_order",
      name: "受注する",
      input: "CustomerInquiry",
      output: "AcceptedOrder",
      status: "defined",
      children: ["receive_inquiry", "create_estimate", "approve_estimate", "accept_order"],
      responsibility: {
        department: "Sales Department",
        company: "Example Construction",
        function: "sales",
        project: "Project A",
      },
    },
    execute_project: {
      id: "execute_project",
      name: "施工する",
      input: "AcceptedOrder",
      output: "CompletedWork",
      status: "defined",
      children: ["plan_construction", "procure_materials", "complete_work"],
      responsibility: {
        department: "Construction Department",
        company: "Example Construction",
        function: "construction",
        project: "Project A",
      },
    },
    bill_customer: {
      id: "bill_customer",
      name: "請求する",
      input: "CompletedWork",
      output: "Invoice",
      status: "defined",
      children: ["issue_invoice"],
      responsibility: {
        department: "Administration Department",
        company: "Example Construction",
        function: "accounting",
        project: "Project A",
      },
    },
    receive_inquiry: {
      id: "receive_inquiry",
      name: "問い合わせを受ける",
      input: "CustomerInquiry",
      output: "EstimateRequest",
      status: "defined",
      responsibility: {
        person: "Sato",
        team: "Sales Team 1",
        section: "Sales Section",
        department: "Sales Department",
        company: "Example Construction",
        function: "sales",
        role: "sales_rep",
        system: "Mail",
        project: "Project A",
      },
    },
    create_estimate: {
      id: "create_estimate",
      name: "見積を作成する",
      input: "EstimateRequest",
      output: "Estimate",
      status: "defined",
      responsibility: {
        person: "Suzuki",
        team: "Estimation Team",
        section: "Estimation Section",
        department: "Sales Department",
        company: "Example Construction",
        function: "sales",
        role: "estimator",
        system: "Spreadsheet",
        project: "Project A",
      },
    },
    approve_estimate: {
      id: "approve_estimate",
      name: "見積を承認する",
      input: "Estimate",
      output: "ApprovedEstimate",
      status: "validated",
      responsibility: {
        person: "Tanaka",
        team: "Sales Team 1",
        section: "Sales Section",
        department: "Sales Department",
        company: "Example Construction",
        function: "sales",
        role: "approver",
        system: "Workflow",
        project: "Project A",
      },
    },
    accept_order: {
      id: "accept_order",
      name: "受注確定する",
      input: "ApprovedEstimate",
      output: "AcceptedOrder",
      status: "validated",
      responsibility: {
        person: "Sato",
        team: "Sales Team 1",
        section: "Sales Section",
        department: "Sales Department",
        company: "Example Construction",
        function: "sales",
        role: "sales_rep",
        system: "kintone",
        project: "Project A",
      },
    },
    plan_construction: {
      id: "plan_construction",
      name: "施工計画を作る",
      input: "AcceptedOrder",
      output: "ConstructionPlan",
      status: "defined",
      responsibility: {
        person: "Ito",
        team: "Construction Planning Team",
        section: "Construction Section",
        department: "Construction Department",
        company: "Example Construction",
        function: "construction",
        role: "planner",
        system: "Planning Board",
        project: "Project A",
      },
    },
    procure_materials: {
      id: "procure_materials",
      name: "材料を手配する",
      input: "ConstructionPlan",
      output: "ProcurementOrder",
      status: "defined",
      responsibility: {
        person: "Kobayashi",
        team: "Procurement Team",
        section: "Procurement Section",
        department: "Construction Department",
        company: "Partner Company",
        function: "procurement",
        role: "buyer",
        system: "EDI",
        project: "Project A",
      },
    },
    complete_work: {
      id: "complete_work",
      name: "施工を完了する",
      input: "ProcurementOrder",
      output: "CompletedWork",
      status: "defined",
      responsibility: {
        person: "Ito",
        team: "Construction Team",
        section: "Construction Section",
        department: "Construction Department",
        company: "Example Construction",
        function: "construction",
        role: "site_manager",
        system: "Field Report",
        project: "Project A",
      },
    },
    issue_invoice: {
      id: "issue_invoice",
      name: "請求書を発行する",
      input: "CompletedWork",
      output: "Invoice",
      status: "automatable",
      responsibility: {
        person: "Yamada",
        team: "Accounting Team",
        section: "Accounting Section",
        department: "Administration Department",
        company: "Example Construction",
        function: "accounting",
        role: "accountant",
        system: "Accounting SaaS",
        project: "Project A",
      },
    },
  },
  flows: [
    { from: "receive_inquiry", to: "create_estimate", contract: "EstimateRequest is complete" },
    { from: "create_estimate", to: "approve_estimate", contract: "Estimate amount is calculated" },
    { from: "approve_estimate", to: "accept_order", contract: "ApprovedEstimate is signed" },
    {
      from: "accept_order",
      to: "plan_construction",
      contract: "AcceptedOrder has construction scope",
    },
    {
      from: "plan_construction",
      to: "procure_materials",
      contract: "ConstructionPlan has material list",
    },
    { from: "procure_materials", to: "complete_work", contract: "ProcurementOrder is fulfilled" },
    { from: "complete_work", to: "issue_invoice", contract: "CompletedWork is accepted" },
  ],
  views: [
    { id: "person_view", layout: "lane", boundary: "person", normalForm: "responsibilityBoundary" },
    {
      id: "section_view",
      layout: "lane",
      boundary: "section",
      normalForm: "responsibilityBoundary",
    },
    {
      id: "department_view",
      layout: "lane",
      boundary: "department",
      normalForm: "responsibilityBoundary",
    },
    {
      id: "company_view",
      layout: "lane",
      boundary: "company",
      normalForm: "responsibilityBoundary",
    },
    {
      id: "project_function_view",
      layout: "lane",
      boundary: ["project", "function"],
      normalForm: "responsibilityBoundary",
    },
  ],
};
